Fix power monitoring tools package dependencies
- Removed netstat (doesn't exist in OE) - replaced with iproute2
- Removed iostat, vmstat (part of sysstat which is already included)
- Removed sensors (part of lm-sensors package)
- Removed cpufrequtils, pm-utils (may not be available)
- Removed kernelshark, ftrace (may not be available)
- Kept essential tools: PowerTOP, IOTop, HTop, Perf, trace-cmd
- Fixed RPROVIDES error that was breaking Build 2106

This resolves the build error:
ERROR: Nothing RPROVIDES 'netstat' but lmp-factory-image RDEPENDS on it